apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-ettersende
  namespace: min-side
  labels:
    team: min-side
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: /person/ettersende/api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /person/ettersende/api/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /person/ettersende/api/internal/metrics
  replicas:
    min: 2
    max: 4
  accessPolicy:
    outbound:
      rules:
        - application: decorator-next
          namespace: personbruker
  ingresses:
    - "https://www.intern.dev.nav.no/person/ettersende"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 384Mi


